package nl.kats.dabo.dsl.enums;

public enum Classification {

		ANORUM,	AKIRA, AMBASSADOR, ANTARES, ATTACK_SHIP,

		BREL, BATTLESHIP, BESTRI, BIRD_OF_PREY, BREEN_WARSHIP, BRENDOB,

		CENTAUR, COMBAT, CONDOR, CONSTITUTION, CUBE,

		DDERIDEX, DKORA, D7, DANUBE, DARMOK, DAUNTLESS, DEFIANT, DELTA_FLYER, DIAMOND, DREXIA,

		EXCELSIOR,

		FREIGHTER,

		GALAXY, GALOR, GUZAHFAR,

		HOPE, HUSNOCK,

		INTERCEPTOR, INTREPID,

		JANITZA, 
		
		KTINGA, KVORT, KELDON, KUMARI, KYANA,

		LANORA,

		MA_KARN, MARAAR, MILITARY_FREIGHTER, MIRANDA,
		
		NA_FAR, NC, NEBULA, NEGH_VAR, NIMARIA, NOREXAN, NOVA, NX,

		ORNATHIA,

		PERIKIAN, PHOENIX, PROMETHEUS,
		
		SCIMITAR, SHABREN, SHUTTLE, SOVEREIGN, SOYUZ, SPHERE,

		TRANSPORT, TYPE8_SHUTTLECRAFT, TYPE9_SHUTTLECRAFT,

		UNKNOWN,

		VINUM, VIRAYLLAN, VORCHA,

		WARSHIP, WELLS,
		
		ZIBALIAN, 
		
}
