package nl.kats.dabo.dsl.enums;

public enum Keyword {
	
	ADMIRAL, ALPHA, ARTIFACT, ASSASSIN, ASSAULT, 

	BAJORAN_RESISTANCE, BLUEGILL,
	
	CADET, CAPTURE, CHANCELLOR, CLOAKING_DEVICE, COMMANDER, COMMODITY, CONSUME, CRIME, 

	DABOGIRL, DECAY, DISSIDENT,	DRONE, 
	
	FOUNDER, 
	
	GATHERER, GENERAL, GENETICALLY_ENHANCED, GLINN, GUL, 

	HAND_WEAPON, HIGH_COUNCIL_MEMBER, HOLOPROGRAM, HOST, 

	INFILTRATION, INFILTRATOR, INTERLINK, 
	
	KAI, 

	LEGATE, 

	MACO, MANEUVER,	MORPH, 

	NEBULA, NUCLEOGENIC, 

	ORB, 
	
	PAH_WRAITH, PARANOIA, PERSISTENT, PRAETOR, PROPHET, PRYLAR, PUNISHMENT, PURSUIT, 

	Q, 

	RECALL, REGION, REPLICATE, RITUAL, RULE, 

	SENATOR, SHAPESHIFTER, SMUGGLER, SPECIES_8472, 

	TEMPORAL, THIEF, TSUNKATSE,
	
	VEDEK, 

	WAITER

}
