package nl.kats.dabo.dsl.enums;

public enum Species {

	ACAMARIAN, ALIEN, ANDORIAN, ANDROID, ANGOSIAN, ATREAN, 
	
	BAKU, BAJORAN, BANDI, BARZAN, BENZITE, BETAZOID, BOLIAN, BORG, BREEN, BREKKIAN, BYNAR, 
	
	CAIRN, CALDONIAN, CARDASSIAN, CHAMELOID, CHANGELING, 
	
	DELTAN, DENOBULAN, DOSI, 
	
	ELAURIAN, ELAYSIAN, 
	
	FARIAN, FERENGI, FLAXIAN, 
	
	GORN, GRAZERITE, 
	
	HEKARAN, HIROGEN, HOLOGRAM, HUMAN, HUPYRIAN, 
	
	IDANIAN, 
	
	JEMHADAR, 
	
	KAREMMA, KELLERUN, KLINGON, KOBLIAD, KREETASSAN, KRENIM, KRIOSIAN, KTARIAN, 
	
	LETHEAN, LURIAN, 
	
	MALON, MARI, MARKALIAN, MINARAN, 
	
	NORCADIAN, 
	
	OCAMPA, ORION, ORNARAN, 
	
	PAKLED, PENDARI, 
	
	RAKHARI, RAMATIN, REMAN, RISAN, ROMULAN, 
	
	SATARRAN, SOLARI, SULIBAN, 
	
	TLANI, TAKARAN, TALAXIAN, TAMARIAN, TANUGAN, TELLARITE, TIBURONIAN, TOSK, TRILL, 
	
	ULLIAN, 
	
	VENTAXIAN, VORGON, VORTA, VULCAN, 
	
	WADI, 
	
	YRIDIAN, 
	
	ZAKDORN, ZALKONIAN, ZIBALIAN

}
